apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scravijk2validator4validator-node
  namespace: scravijk2-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: scravijk2validator4validator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_validator
    sourceRef:
      kind: GitRepository
      name: flux-besu-ravijk2
      namespace: flux-besu-ravijk2
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://29ad27c1cb51bcae6c5d9c051369c6fe1f83ebfa5f5a0e244096e91b65d4a277cbd29da7cdf76acdcdcefc2f446254327a20407181f9cca2bf81c4b11092ce01@validator1.beveldev.dev.aws.blockchaincloudpoc-develop.com:15081"
      - "enode://38692a967a300db35a3460f8325dfc4c8dbca3f58ca53f14d3760ec6d0041510f0190fa0d0f449e8dc035a467dbef40c952f9c74dbf1ad6de148b348111b0a15@validator2.beveldev.dev.aws.blockchaincloudpoc-develop.com:15083"
      - "enode://3e1d44c61b2a6fa38939928e6bf15960fdae8e6dd350aaaec27001e12770dcc76ecea79785800c80c679be5e4d60fb86d1470254d0546f7c40a32b12b973b73f@validator3.beveldev.dev.aws.blockchaincloudpoc-develop.com:15085"
      - "enode://8018dd84daece65ac90685952cb7a93c0d13cedf7a2b0e3bd4e2d9a9d93fcef6500ae43f7d7de3070f6de36d774aaa8675a469100ac07c8f30e550ece52f6318@validator4.beveldev.dev.aws.blockchaincloudpoc-develop.com:15087"
      - "enode://887132fa400c9462fc7a7f899c855bcb7d20cbe12ee73563cdd0b45741a53831a32df6d8c9f16db639f25f691bc744a9b1b4d454d86a30e249b5f855ae81913f@cravijk2.beveldev.dev.aws.blockchaincloudpoc-develop.com:15089"

    metadata:
      namespace: scravijk2-bes
      labels:

    ambassador:
      external_url_suffix: beveldev.dev.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
    proxy:
      provider: ambassador
      external_url: scravijk2.beveldev.dev.aws.blockchaincloudpoc-develop.com
      p2p: 15087
      rpc: 15088

    images:
      node: hyperledger/besu:22.10.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: validator4
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

      permissioning:
        enabled: False
      
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretprefix: secretsv2/data/scravijk2-bes/crypto/validator4
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besuscravijk2

    genesis: ewogICAiY29uZmlnIjogewogICAgICJjaGFpbklkIjogIDIwMTgsCiAgICAgImNvbnN0YW50aW5vcGxlZml4YmxvY2siOiAwLAogICAgICJjb250cmFjdFNpemVMaW1pdCI6IDIxNDc0ODM2NDcsCiAgICAgImliZnQyIjogewogICAgICAgImJsb2NrcGVyaW9kc2Vjb25kcyI6IDIsCiAgICAgICAiZXBvY2hsZW5ndGgiOiAzMDAwMCwKICAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgIH0KICAgfSwKICAgIm5vbmNlIjogIjB4MCIsCiAgICJ0aW1lc3RhbXAiOiAiMHg1OGVlNDBiYSIsCiAgICJnYXNMaW1pdCI6ICIweDFmZmZmZmZmZmZmZmZmIiwKICAgImRpZmZpY3VsdHkiOiAiMHgxIgp9


    metrics:
      enabled: False
      port: 9545    
