##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
dependency:
  name: galaxy
driver:
  name: docker
lint: |   
  yamllint .
platforms:
  - name: kind-default
    groups:
    - k8s
    image: bsycorp/kind:latest-1.19
    privileged: true
    pre_build_image: yes
provisioner:
  name: ansible
  log: True
  lint: |
    ansible-lint
  env:
    K8S_AUTH_KUBECONFIG: /tmp/molecule/kind-default/kubeconfig
    KUBECONFIG: /tmp/molecule/kind-default/kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
verifier:
  name: ansible
  lint: |
    ansible-lint
