---
# tasks file for ./vault-script
- name: "check for the configmap  vault-script to be created"
  k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: "{{ component_ns }}"
    name: bevel-vault-script
  register: bevel-vault-script

- name: "Create configmap for bevel-vault-script"
  helm:
    name: bevel-vault-script
    chart_ref: "{{ playbook_dir }}/../../shared/charts/vault-script"
    create_namespace: true
    values: 
      namespace: "{{ component_ns }}"