apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cravijk2-ambassador-job
  namespace: cravijk2-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: cravijk2-ambassador-job
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/generate_ambassador_certs
    sourceRef:
      kind: GitRepository
      name: flux-besu-ravijk2
      namespace: flux-besu-ravijk2
  values:
    metadata:
      name: cravijk2-ambassador-job
      namespace: cravijk2-bes
    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: regcred
      pullPolicy: IfNotPresent
    network:
      tmtls: True
    node:
      name: cravijk2
      clientport: 8888
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      authpath: besucravijk2
      rootcasecret: secretsv2/data/cravijk2-bes/crypto/ambassadorcerts/rootca
      ambassadortlssecret: secretsv2/data/cravijk2-bes/crypto/cravijk2/tls
      role: vault-role
      serviceaccountname: vault-auth
      type: hashicorp
    subject:
      ambassadortls: CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB
    opensslVars:
      domain_name_pub: cravijk2.beveldev.dev.aws.blockchaincloudpoc-develop.com
      domain_name_priv: cravijk2.cravijk2-bes
      domain_name_tessera: cravijk2-tessera.cravijk2-bes
    healthcheck:
      retries: 10
      sleepTimeAfterError: 2

