apiVersion:  helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cravijk2tessera
  namespace: cravijk2-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: cravijk2tessera
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_tessera
    sourceRef:
      kind: GitRepository
      name: flux-besu-ravijk2
      namespace: flux-besu-ravijk2
  values:
    replicaCount: 1
    metadata:
      namespace: cravijk2-bes
      labels:
    images:
      alpineutils: ghcr.io/hyperledger/bevel-alpine-ext:latest
      tessera: quorumengineering/tessera:hashicorp-21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    tessera:
      name: cravijk2-tessera
      dbname: demodb
      dburl: "jdbc:mysql://cravijk2-tessera:3306/demodb"
      dbusername: demouser
      tls: "STRICT"
      url: "https://cravijk2.beveldev.dev.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "https://cravijk2-tessera:8888"
      othernodes:
        - url: https://cravijk2.beveldev.dev.aws.blockchaincloudpoc-develop.com
      trust: "CA_OR_TOFU"

      servicetype: ClusterIP
      ports:
        tm: 443
        db: 3306
        client: 8888
      mountPath: /etc/tessera/data
      ambassadorSecret: cravijk2-ambassador-certs
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:20002
      secretengine: secretsv2
      tmsecretpath: cravijk2-bes/crypto/cravijk2/tm
      secretprefix: secretsv2/data/cravijk2-bes/crypto/cravijk2
      serviceaccountname: vault-auth
      keyname: credentials
      type: hashicorp
      tm_keyname: tm
      tlsdir: tls
      role: vault-role
      authpath: besucravijk2
    proxy:
      provider: "ambassador"
      external_url: cravijk2.beveldev.dev.aws.blockchaincloudpoc-develop.com
      portTM: 443
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi


    metrics:
      enabled: False
      port: 9545
